---
repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
    # -   id: identity  # Prints all files passed to pre-commits. Debugging.
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.29.0
    hooks:
      - id: yamllint
  - repo: https://github.com/lyz-code/yamlfix
    rev: 1.8.0
    hooks:
      - id: yamlfix
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        args: [--maxkb=100]
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-vcs-permalinks
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: no-commit-to-branch
        args: [--branch, main]
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-mock-methods
      - id: python-no-eval
      - id: python-no-log-warn
      - id: python-use-type-annotations
      - id: text-unicode-replacement-char
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
      - id: reorder-python-imports
        args: [--py37-plus, --add-import, from __future__ import annotations]
  - repo: https://github.com/asottile/setup-cfg-fmt
    rev: v2.2.0
    hooks:
      - id: setup-cfg-fmt
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        exclude: src/dcegm/upper_envelope_fast_org.py
  - repo: https://github.com/PyCQA/docformatter
    rev: v1.5.1
    hooks:
      - id: docformatter
        args:
          - --in-place
          - --wrap-summaries
          - '88'
          - --wrap-descriptions
          - '88'
          - --blank
        exclude: src/dcegm/upper_envelope_fast_org.py
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.254
    hooks:
      - id: ruff
        exclude: |
          (?x)^(
              src/dcegm/sandbox/benchmark_cases.ipynbpath/to/file1.py|
              docs/source/conf.py|
          )$
  - repo: https://github.com/dosisod/refurb
    rev: v1.13.0
    python-version: 3.10
    hooks:
      - id: refurb
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.6.1
    hooks:
      - id: nbqa-black
      - id: nbqa-ruff
        exclude: src/dcegm/sandbox/benchmark_cases.ipynb
  - repo: https://github.com/econchick/interrogate
    rev: 1.5.0
    hooks:
      - id: interrogate
        args: [-v, --fail-under=75]
        exclude: ^(tests/|docs/|scripts/)
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.16
    hooks:
      - id: mdformat
        additional_dependencies: [mdformat-gfm, mdformat-black]
        args: [--wrap, '88']
        files: (README\.md)
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.2
    hooks:
      - id: codespell
        additional_dependencies: [tomli]
        exclude: src/dcegm/sandbox/benchmark_cases.ipynb
# -   repo: https://github.com/mgedmin/check-manifest
#     rev: "0.49"
#     hooks:
#     -   id: check-manifest
#         args: [--no-build-isolation]
#         additional_dependencies: [setuptools-scm, toml]
ci:
  autoupdate_schedule: monthly
