---
codecov:
  notify:
    require_ci_to_pass: true
coverage:
  precision: 2
  round: down
  range: 60...100
  status:
    patch:
      default:
        target: 70%
    project:
      default:
        target: 90%
ignore:
  - .tox/**/*
  - setup.py
  - src/dcegm/fast_upper_envelope.py
  - tests/utils/upper_envelope_fedor.py
  - tests/utils/fast_upper_envelope_org.py
  - tests/conftest.py
