codecov:
  branch: main
coverage:
  precision: 2
  round: down
  range: 80...100
  status:
    status:
    patch:
      default:
        target: 70%
    project:
      default:
        target: 90%
        
ignore: [.tox/**/*, setup.py]