name: dcegm

channels:
  - conda-forge
  - defaults

dependencies:
  - python>=3.9
  - pip
  - pytest
  - pytest-cov

  # Package dependencies
  - estimagic
  - numpy
  - scipy
  - numba
  - pandas
  - jax
  - networkx

  # Misc
  - jupyterlab
  - matplotlib
  - black
  - flake8
  - pdbpp
  - pre-commit
  - setuptools_scm
  - toml

  # Conda
  - anaconda-client
  - conda-build
  - conda-verify
  - tox-conda

  # docs
  - pip:
      - furo
