name: dcegm

channels:
  - defaults
  - conda-forge

dependencies:
  - python >=3.7
  - pip
  - pytest
  - pytest-cov

  # Package dependencies
  - estimagic
  - numpy
  - scipy
  - numba
  - pandas
  - jax
  - networkx

  # Misc
  - black
  - flake8
  - pdbpp
  - pre-commit
  - setuptools_scm
  - toml

  # Conda
  - anaconda-client
  - conda-build
  - conda-verify
  - tox-conda
