name: dcegm

channels:
  - defaults
  - conda-forge

dependencies:
  - python >= 3.6
  - pip
  - pytest

  - jupyterlab
  - nb_conda_kernels
  - nb_black

  - numpy 
  - pandas
  - scipy

  - matplotlib

  - black
  - flake8
  - pdbpp
  - pre-commit

  - setuptools_scm
  - toml

  # Conda
  - anaconda-client
  - conda-build
  - conda-verify

  - pytest-cov
  - tox-conda
